# Jekyll & Minimal Mistakes Theme configuration
# For more information, please refer to https://mmistakes.github.io/minimal-mistakes/docs/configuration/


# Theme Skin configuration
minimal_mistakes_skin    : "custom"


# Blog Metadata configuration
locale                   : "ko-KR"
rtl                      : false
title                    : "개구리의 밀실"
title_separator          : "|"
subtitle                 : 
name                     : "Hyeon Wuk Park"
description              : "개구리만의 약간의 생각과 약간의 일상을 공유하는 밀실입니다. 오늘도 개구리의 밀실에 함께해 주신 여러분을 환영합니다."
url                      : "https://trail3r.github.io"
baseurl                  : ""
repository               : "trail3r/trail3r.github.io"
teaser                   : 
logo                     : 
masthead_title           : 
breadcrumbs              : false
words_per_minute         : 100
enable_copy_code_button  : false
copyright                : 
copyright_url            : 


# Comment configuration
comments:
  provider               : "giscus"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : "R_kgDORV08tA"
    category_name        : "Comments"
    category_id          : "DIC_kwDORV08tM4C3d8g"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "light_protanopia"
    strict               : "0"
    input_position       : "bottom"
    emit_metadata        : "0"
    lang                 : "ko"
    lazy                 : false
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"


# Security (Captcha) configuration
reCaptcha:
  siteKey                :
  secret                 :



# ATOM Feed configuration
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)


# Search function configuration
search                   : true
search_full_content      : true
search_provider          : lunr

lunr:
  search_within_pages    : # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true


# SEO search engine configuration
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :


# SNS share information configuration
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "/assets/images/posts/Featured/Brochure/teaser.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Person"
  name                   : "개구리"
  links:
    - "https://blog.naver.com/trail3r"
    - "https://github.com/trail3r"
    - "https://instagram.com/trail3r__"


# Blog analytics tool configuration
analytics:
  provider               : # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Author profile configuration
author:
  name             : "개구리"
  avatar           : "assets/images/signatures/minecraft_frog.png"
  bio              : "우물 안 개구리의 일상과 생각 그리고 성장을 그리는 우물 탈출기"
  # location         : "대한민국 (South Korea)"
  # email            :
  links:
    - label: "Gmail"
      icon: "assets/images/logos/gmail.svg"
      url: "mailto:gusdnr7223@gmail.com"
    - label: "네이버 블로그"
      icon: "assets/images/logos/naver-blog.svg"
      url: "https://blog.naver.com/trail3r"
    - label: "GitHub"
      icon: "assets/images/logos/github.svg"
      url: "https://github.com/trail3r"
    - label: "Instagram"
      icon: "assets/images/logos/instagram.svg"
      url: "https://instagram.com/trail3r__"


# Footer configuration
footer:
  links:
    - label: "네이버 블로그"
      icon: "assets/images/logos/naver-blog.svg"
      url: "https://blog.naver.com/trail3r"
    - label: "GitHub"
      icon: "assets/images/logos/github.svg"
      url: "https://github.com/trail3r"
    - label: "Instagram"
      icon: "assets/images/logos/instagram.svg"
      url: "https://instagram.com/trail3r__"
  since: "2026"


# File recognition configuration
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/minimal_mistakes
  - assets/js/plugins
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs  # ignore Minimal Mistakes /docs
  - /test  # ignore Minimal Mistakes /test
  - assets/tree_sitter_parsers  # ignore Tree-Sitter Parser
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Markdown processing configuration
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown configuration
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: tree-sitter
  syntax_highlighter_opts:
    tree_sitter_parsers_dir: "assets/tree_sitter_parsers"
    css_classes: true


# Sass configuration
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  quiet_deps: true
  silence_deprecations:
    - import


# URL Metadata configuration
url_metadata:
  open_timeout: 3
  read_timeout: 5


# Output configuration
permalink: /:categories/:title/
timezone: Asia/Seoul


# jekyll-paginate-v2 configuration
# For more information, please refer to https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  # Set enabled to true to use paginate v2
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title'  # default: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2


# Plugins configuration
plugins:
  - kramdown/syntax_tree_sitter
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-url-metadata

whitelist:
  - kramdown/syntax_tree_sitter
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-url-metadata


# Archive configuration
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML compression configuration (https://jch.penibelst.de/)
compress_html:
  clippings: all
  ignore:
    envs: development


# Default values configuration
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: false
      active_sidebar: false
      read_time: false
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      active_sidebar: false
      read_time: false
      comments: false
      share: true
      related: false

date_format: "%Y. %m. %d."
